### PR TITLE
Fixes for adding Yii 2 to awesome list

### PR DESCRIPTION
**Pull request by TheAdnan**
Changes for the requirements mentioned in this Pull Request: [PR](https://github.com/sindresorhus/awesome/pull/1086).

Also, please notify me when you add the topics _awesome_ and _awesome-list_ to the repo (issue #22 ).

### CODE REVIEW

**Comment by samdark** [comment]
You should be notified by GitHub automatically.

**Comment by TheAdnan** [comment]
Oh yeah, you're right, I'm sorry 😃

**Comment by mnglkhn** [comment]
It is a personal opinion, but I think that keeping **Yii2** instead of **Yii 2** helps with SEO and the marketing of Yii. As long as Yii1 (or Yii) is still around, people can differentiate between the two only by searching for the **Yii2**  term

**Comment by TheAdnan** [comment]
@mnglkhn I wasn't actually sure which approach to take, but I went with **Yii 2** in the end.

**Comment by TheAdnan** [comment]
@samdark

**Comment by samdark** [comment]
What? I'm OK with these changes since 19th October. You should see big green "Squash an merge" button so press it.

**Comment by TheAdnan** [comment]
@samdark 
sshot I actually don't have write access :)

**Comment by samdark** [comment]
Oh :)

**Comment by loveorigami** [comment]
I am also don't see button in my PR
#21

**Pull request merged**
